### PR TITLE
Fix GitHub actions

### PR DESCRIPTION
**Pull request by DePasqualeOrg**
The current GitHub actions appear to be failing, maybe because they include Swift 5.8. I also included a swift-format step.

### CODE REVIEW

**Comment by DePasqualeOrg** [comment]
Now this works.

**Comment by DePasqualeOrg** [comment]
I added the same pre-commit hook as in mlx-swift, so that you can run the following command to format before committing: `pre-commit run --all-files`

**Comment by johnmai-dev** [comment]
> Now this works.
> 
> Regarding the formatting rules: Would you mind if we remove `lineBreakBeforeControlFlowKeywords`? I find the code more difficult to read with this setting enabled, and I think most Swift code does not use this rule, but it's also a matter of personal taste.

You can remove it.

**Comment by DePasqualeOrg** [comment]
Okay, I think this is ready to go.

**Comment by DePasqualeOrg** [comment]
@johnmai-dev, once you're able to merge this, I'll rebase my previous PR to make it easier for @pcuenca to review it.

**Review by johnmai-dev — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
